


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."championship" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."championship" OWNER TO "postgres";


ALTER TABLE "public"."championship" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."championship_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."player" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."player" OWNER TO "postgres";


ALTER TABLE "public"."player" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."player_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."prediction" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "player_id" integer NOT NULL,
    "prediction_item_id" integer NOT NULL,
    "value" json NOT NULL
);


ALTER TABLE "public"."prediction" OWNER TO "postgres";


ALTER TABLE "public"."prediction" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."prediction_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."prediction_item" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "round_id" integer NOT NULL,
    "question" "text",
    "options" json,
    "correct_answer" json,
    "tie_breaker" boolean DEFAULT false NOT NULL,
    "points" smallint
);


ALTER TABLE "public"."prediction_item" OWNER TO "postgres";


ALTER TABLE "public"."prediction_item" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."prediction_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."round" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "championship_id" integer NOT NULL,
    "name" "text" NOT NULL,
    "points" smallint NOT NULL,
    "end_time" timestamp with time zone,
    "current" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."round" OWNER TO "postgres";


ALTER TABLE "public"."round" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."round_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."championship"
    ADD CONSTRAINT "championship_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."championship"
    ADD CONSTRAINT "championship_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."player"
    ADD CONSTRAINT "player_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prediction_item"
    ADD CONSTRAINT "prediction_item_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prediction"
    ADD CONSTRAINT "prediction_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."round"
    ADD CONSTRAINT "round_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prediction_item"
    ADD CONSTRAINT "prediction_item_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "public"."round"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prediction"
    ADD CONSTRAINT "prediction_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prediction"
    ADD CONSTRAINT "prediction_prediction_item_id_fkey" FOREIGN KEY ("prediction_item_id") REFERENCES "public"."prediction_item"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."round"
    ADD CONSTRAINT "round_championship_id_fkey" FOREIGN KEY ("championship_id") REFERENCES "public"."championship"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."championship" TO "anon";
GRANT ALL ON TABLE "public"."championship" TO "authenticated";
GRANT ALL ON TABLE "public"."championship" TO "service_role";



GRANT ALL ON SEQUENCE "public"."championship_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."championship_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."championship_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."player" TO "anon";
GRANT ALL ON TABLE "public"."player" TO "authenticated";
GRANT ALL ON TABLE "public"."player" TO "service_role";



GRANT ALL ON SEQUENCE "public"."player_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."player_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."player_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."prediction" TO "anon";
GRANT ALL ON TABLE "public"."prediction" TO "authenticated";
GRANT ALL ON TABLE "public"."prediction" TO "service_role";



GRANT ALL ON SEQUENCE "public"."prediction_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prediction_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prediction_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."prediction_item" TO "anon";
GRANT ALL ON TABLE "public"."prediction_item" TO "authenticated";
GRANT ALL ON TABLE "public"."prediction_item" TO "service_role";



GRANT ALL ON SEQUENCE "public"."prediction_item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prediction_item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prediction_item_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."round" TO "anon";
GRANT ALL ON TABLE "public"."round" TO "authenticated";
GRANT ALL ON TABLE "public"."round" TO "service_role";



GRANT ALL ON SEQUENCE "public"."round_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."round_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."round_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































